apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

patches:
  - path: patch-image.yaml
    target:
      kind: Deployment
      name: website

  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: website-ingress

  - path: patch-service.yaml
    target:
      kind: Ingress
      name: website-service
