apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - ../../base

namespace: website-dev

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-image.yaml
  - patch-ingress.yaml
