apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
      name: website
  - path: patch-image.yaml
    target:
      kind: Deployment
      name: website
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: website-ingress
